version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: BD_Hospital
    environment:
      POSTGRES_DB: hospitais
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
    ports:
      - "3030:5432"
    restart: always